update workflow

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -41,11 +41,25 @@ jobs:
     - name: Create release
       run: .\ci\create-release.ps1
 
+    - name: Create game-specific release
+      run: |
+        $scriptPath = "games/ci/$env:GAME_NAME/create-release.ps1"
+        
+        if (Test-Path $scriptPath) {
+          Write-Host "🚀 Running game-specific release script for: $env:GAME_NAME"
+          try {
+            & $scriptPath
+          } catch {
+            Write-Error "❌ Failed to execute script at $scriptPath : $_"
+            exit 1
+          }
+        } else {
+          Write-Host "⚠️ No specific release script found at $scriptPath. Skipping."
+        }
+
     - name: Cleanup draft v0.0.0 releases
       if: env.ACT == 'true' && startsWith(github.ref, 'refs/tags/') && github.ref_name == 'v0.0.0'
       run: .\ci\cleanup-draft-releases.ps1 '${{ github.repository }}'
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     - name: GH Release
       uses: softprops/action-gh-release@v2.0.4
