ci

diff --git a/.github/workflows/on-new-release.yml b/.github/workflows/on-new-release.yml
--- a/.github/workflows/on-new-release.yml
+++ b/.github/workflows/on-new-release.yml
@@ -25,19 +25,57 @@ jobs:
     runs-on: windows-latest
     
     steps:
+    - name: Init
+      run: |
+        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
+
     - name: Show release info
       run: |
-        Write-Host "Release tag: ${{ github.event.release.tag_name }}"
-        Write-Host "Release name: ${{ github.event.release.name }}"
-        Write-Host "Ref name: ${{ github.ref_name }}"
-        Write-Host "Is draft: ${{ github.event.release.draft }}"
+        Write-Output "Release tag: ${{ github.event.release.tag_name }}"
+        Write-Output "Release name: ${{ github.event.release.name }}"
+        Write-Output "Ref name: ${{ github.ref_name }}"
+        Write-Output "Is draft: ${{ github.event.release.draft }}"
 
     - name: Checkout
       uses: actions/checkout@v4
 
     - name: Set environment variables
-      run: .\ci\set-vars.ps1 -github_ref_name '${{ github.ref_name }}' -github_repository $env:GITHUB_REPOSITORY
+      run: |
+        .\ci\set-vars.ps1 -github_ref_name '${{ github.ref_name }}' -github_repository $env:GITHUB_REPOSITORY
 
     - name: Create index.json metadata
       run: |
         .\ci\create-index-metadata.ps1
+
+    - name: Commit index.json
+      run: |
+        $file = "resources/index.json"
+        
+        git config --local user.email "github-actions[bot]@users.noreply.github.com"
+        git config --local user.name "github-actions[bot]"
+
+        if (Test-Path $file) {
+            $status = git status --porcelain $file
+            if ($null -eq $status) {
+                Write-Warning "⚠️ No changes detected in $file. Skipping commit."
+                return 
+            }
+
+            $tag = $env:GITHUB_REF_NAME
+            $msg = "ci: update index.json for release $tag [skip ci]"
+
+            git add $file
+
+            if ($env:ACT -eq "true") {
+                Write-Output "🧪 ACT detected: performing dry-run commit..."
+                git commit -m "$msg (dry run)" --dry-run
+                git status --short
+            } else {
+                Write-Output "🚀 Pushing changes to repository..."
+                git commit -m $msg
+                git push
+            }
+        } else {
+            Write-Error "❌ File $file not found. Nothing to commit."
+            exit 1
+        }
